; Listing generated by Microsoft (R) Optimizing Compiler Version 19.51.36260.0 

include listing.inc

INCLUDELIB LIBCMT
INCLUDELIB OLDNAMES

PUBLIC	__local_stdio_printf_options
PUBLIC	_vfprintf_l
PUBLIC	fprintf
PUBLIC	main
PUBLIC	??_C@_0CN@HBIOMAF@Failed?5to?5initialize?5Wooting?5Ana@ ; `string'
PUBLIC	??_C@_0CD@NIDKDOEG@Failed?5to?5read?5analog?5key?5values@ ; `string'
PUBLIC	??_C@_0BH@KOHKNOHN@SendInput?5failed?3?5?$CFlu?6@ ; `string'
PUBLIC	__real@3f800000
PUBLIC	__real@40800000
EXTRN	__acrt_iob_func:PROC
EXTRN	__stdio_common_vfprintf:PROC
EXTRN	clock:PROC
EXTRN	__imp_GetLastError:PROC
EXTRN	__imp_Sleep:PROC
EXTRN	__imp_SendInput:PROC
EXTRN	wooting_analog_initialise:PROC
EXTRN	wooting_analog_is_initialised:PROC
EXTRN	wooting_analog_uninitialise:PROC
EXTRN	wooting_analog_read_analog:PROC
EXTRN	_fltused:DWORD
_DATA	SEGMENT
COMM	?_OptionsStorage@?1??__local_stdio_printf_options@@9@9:QWORD							; `__local_stdio_printf_options'::`2'::_OptionsStorage
_DATA	ENDS
_BSS	SEGMENT
?start@?1??main@@9@9 DD 01H DUP (?)			; `main'::`2'::start
?dt@?1??main@@9@9 DD 01H DUP (?)			; `main'::`2'::dt
_BSS	ENDS
;	COMDAT pdata
pdata	SEGMENT
$pdata$_vfprintf_l DD imagerel $LN4
	DD	imagerel $LN4+57
	DD	imagerel $unwind$_vfprintf_l
pdata	ENDS
;	COMDAT pdata
pdata	SEGMENT
$pdata$fprintf DD imagerel $LN6
	DD	imagerel $LN6+68
	DD	imagerel $unwind$fprintf
pdata	ENDS
;	COMDAT pdata
pdata	SEGMENT
$pdata$main DD	imagerel $LN36
	DD	imagerel $LN36+71
	DD	imagerel $unwind$main
pdata	ENDS
;	COMDAT pdata
pdata	SEGMENT
$pdata$8$main DD imagerel $LN36+71
	DD	imagerel $LN36+649
	DD	imagerel $chain$8$main
pdata	ENDS
;	COMDAT pdata
pdata	SEGMENT
$pdata$10$main DD imagerel $LN36+649
	DD	imagerel $LN36+687
	DD	imagerel $chain$10$main
pdata	ENDS
;	COMDAT pdata
pdata	SEGMENT
$pdata$11$main DD imagerel $LN36+687
	DD	imagerel $LN36+729
	DD	imagerel $chain$11$main
pdata	ENDS
;	COMDAT __real@40800000
CONST	SEGMENT
__real@40800000 DD 040800000r			; 4
CONST	ENDS
;	COMDAT __real@3f800000
CONST	SEGMENT
__real@3f800000 DD 03f800000r			; 1
CONST	ENDS
;	COMDAT ??_C@_0BH@KOHKNOHN@SendInput?5failed?3?5?$CFlu?6@
CONST	SEGMENT
??_C@_0BH@KOHKNOHN@SendInput?5failed?3?5?$CFlu?6@ DB 'SendInput failed: %'
	DB	'lu', 0aH, 00H				; `string'
CONST	ENDS
;	COMDAT ??_C@_0CD@NIDKDOEG@Failed?5to?5read?5analog?5key?5values@
CONST	SEGMENT
??_C@_0CD@NIDKDOEG@Failed?5to?5read?5analog?5key?5values@ DB 'Failed to r'
	DB	'ead analog key values.', 0aH, 00H		; `string'
CONST	ENDS
;	COMDAT ??_C@_0CN@HBIOMAF@Failed?5to?5initialize?5Wooting?5Ana@
CONST	SEGMENT
??_C@_0CN@HBIOMAF@Failed?5to?5initialize?5Wooting?5Ana@ DB 'Failed to ini'
	DB	'tialize Wooting Analog SDK: %d', 0aH, 00H	; `string'
CONST	ENDS
;	COMDAT xdata
xdata	SEGMENT
$chain$11$main DD 021H
	DD	imagerel $LN36
	DD	imagerel $LN36+71
	DD	imagerel $unwind$main
xdata	ENDS
;	COMDAT xdata
xdata	SEGMENT
$chain$10$main DD 0120021H
	DD	05e800H
	DD	06d800H
	DD	07c800H
	DD	08b800H
	DD	09a800H
	DD	0a9800H
	DD	0b8800H
	DD	0c7800H
	DD	0d6800H
	DD	imagerel $LN36
	DD	imagerel $LN36+71
	DD	imagerel $unwind$main
xdata	ENDS
;	COMDAT xdata
xdata	SEGMENT
$chain$8$main DD 0125121H
	DD	05e851H
	DD	06d84bH
	DD	07c841H
	DD	08b837H
	DD	09a82eH
	DD	0a9825H
	DD	0b881cH
	DD	0c7813H
	DD	0d6808H
	DD	imagerel $LN36
	DD	imagerel $LN36+71
	DD	imagerel $unwind$main
xdata	ENDS
;	COMDAT xdata
xdata	SEGMENT
$unwind$main DD	030901H
	DD	01c0109H
	DD	03002H
xdata	ENDS
;	COMDAT xdata
xdata	SEGMENT
$unwind$fprintf DD 041601H
	DD	070125216H
	DD	030106011H
xdata	ENDS
;	COMDAT xdata
xdata	SEGMENT
$unwind$_vfprintf_l DD 050901H
	DD	070056209H
	DD	050036004H
	DD	03002H
xdata	ENDS
; Function compile flags: /Ogtpy
; File C:\Program Files (x86)\Windows Kits\10\include\10.0.26100.0\ucrt\corecrt_stdio_config.h
;	COMDAT __local_stdio_printf_options
_TEXT	SEGMENT
__local_stdio_printf_options PROC			; COMDAT

; 91   :         static unsigned __int64 _OptionsStorage;
; 92   :         return &_OptionsStorage;

	lea	rax, OFFSET FLAT:?_OptionsStorage@?1??__local_stdio_printf_options@@9@9 ; `__local_stdio_printf_options'::`2'::_OptionsStorage

; 93   :     }

	ret	0
__local_stdio_printf_options ENDP
_TEXT	ENDS
; Function compile flags: /Ogtpy
; File C:\Program Files (x86)\Windows Kits\10\include\10.0.26100.0\ucrt\stdio.h
;	COMDAT _vfprintf_l
_TEXT	SEGMENT
_Stream$ = 96
_Format$ = 104
_Locale$ = 112
_ArgList$ = 120
_vfprintf_l PROC					; COMDAT

; 644  :     {

$LN4:
	push	rbx
	push	rbp
	push	rsi
	push	rdi
	sub	rsp, 56					; 00000038H
	mov	rbx, r9
	mov	rdi, r8
	mov	rsi, rdx
	mov	rbp, rcx

; 645  :         return __stdio_common_vfprintf(_CRT_INTERNAL_LOCAL_PRINTF_OPTIONS, _Stream, _Format, _Locale, _ArgList);

	call	__local_stdio_printf_options
	mov	r9, rdi
	mov	QWORD PTR [rsp+32], rbx
	mov	r8, rsi
	mov	rdx, rbp
	mov	rcx, QWORD PTR [rax]
	call	__stdio_common_vfprintf

; 646  :     }

	add	rsp, 56					; 00000038H
	pop	rdi
	pop	rsi
	pop	rbp
	pop	rbx
	ret	0
_vfprintf_l ENDP
_TEXT	ENDS
; Function compile flags: /Ogtpy
; File C:\Program Files (x86)\Windows Kits\10\include\10.0.26100.0\ucrt\stdio.h
;	COMDAT fprintf
_TEXT	SEGMENT
_Stream$ = 80
_Format$ = 88
fprintf	PROC						; COMDAT

; 837  :     {

$LN6:
	mov	QWORD PTR [rsp+16], rdx
	mov	QWORD PTR [rsp+24], r8
	mov	QWORD PTR [rsp+32], r9
	push	rbx
	push	rsi
	push	rdi
	sub	rsp, 48					; 00000030H
	mov	rdi, rdx

; 838  :         int _Result;
; 839  :         va_list _ArgList;
; 840  :         __crt_va_start(_ArgList, _Format);

	lea	rsi, QWORD PTR _Format$[rsp+8]
	mov	rbx, rcx

; 645  :         return __stdio_common_vfprintf(_CRT_INTERNAL_LOCAL_PRINTF_OPTIONS, _Stream, _Format, _Locale, _ArgList);

	call	__local_stdio_printf_options
	xor	r9d, r9d
	mov	QWORD PTR [rsp+32], rsi
	mov	r8, rdi
	mov	rdx, rbx
	mov	rcx, QWORD PTR [rax]
	call	__stdio_common_vfprintf

; 841  :         _Result = _vfprintf_l(_Stream, _Format, NULL, _ArgList);
; 842  :         __crt_va_end(_ArgList);
; 843  :         return _Result;
; 844  :     }

	add	rsp, 48					; 00000030H
	pop	rdi
	pop	rsi
	pop	rbx
	ret	0
fprintf	ENDP
_TEXT	ENDS
; Function compile flags: /Ogtpy
; File C:\Users\Jason\Documents\wootang\wootang.c
;	COMDAT main
_TEXT	SEGMENT
input$ = 32
main	PROC						; COMDAT

; 25   : int main(void) {

$LN36:
	push	rbx
	sub	rsp, 224				; 000000e0H
	xorps	xmm0, xmm0

; 26   :     //initialize variables
; 27   :     static clock_t start, dt;
; 28   :     float dx, dy; float accel = 1.0f; //default accel value
; 29   :     float analog_w, analog_a, analog_s, analog_d;
; 30   :     int init_result;
; 31   :     keyput x = {0.0f, 0.0f};
; 32   :     keyput y = {0.0f, 0.0f};
; 33   :     //windows stuff
; 34   :     INPUT input = {0};
; 35   :     input.type = INPUT_MOUSE;

	mov	DWORD PTR input$[rsp], 0
	xorps	xmm1, xmm1

; 36   :     input.mi.dwFlags = MOUSEEVENTF_MOVE;

	mov	DWORD PTR input$[rsp+20], 1
	movdqu	XMMWORD PTR input$[rsp+4], xmm0
	movdqu	XMMWORD PTR input$[rsp+24], xmm1

; 37   : 
; 38   :     //code
; 39   :     init_result = wooting_analog_initialise();

	call	wooting_analog_initialise
	mov	ebx, eax

; 40   :     if (init_result < 0 || !wooting_analog_is_initialised()) {

	test	eax, eax
	js	$LN5@main
	call	wooting_analog_is_initialised
	test	al, al
	je	$LN5@main
	movaps	XMMWORD PTR [rsp+208], xmm6
	xorps	xmm6, xmm6
	movaps	XMMWORD PTR [rsp+192], xmm7
	movaps	XMMWORD PTR [rsp+176], xmm8
	movaps	XMMWORD PTR [rsp+160], xmm9
	movaps	XMMWORD PTR [rsp+144], xmm10
	movaps	XMMWORD PTR [rsp+128], xmm11
	xorps	xmm11, xmm11
	movaps	XMMWORD PTR [rsp+112], xmm12
	xorps	xmm12, xmm12
	movaps	XMMWORD PTR [rsp+96], xmm13
	movaps	XMMWORD PTR [rsp+80], xmm14

; 42   :         return 1;
; 43   :     }
; 44   : 
; 45   :     while (1) {
; 46   :         start = clock(), dt;

	call	clock

; 47   : 
; 48   :         //get analog values
; 49   :         analog_w = wooting_analog_read_analog(KEY_W);

	mov	ecx, 26
	mov	DWORD PTR ?start@?1??main@@9@9, eax
	call	wooting_analog_read_analog

; 50   :         analog_a = wooting_analog_read_analog(KEY_A);

	mov	ecx, 4
	movaps	xmm10, xmm0
	call	wooting_analog_read_analog

; 51   :         analog_s = wooting_analog_read_analog(KEY_S);

	mov	ecx, 22
	movaps	xmm9, xmm0
	call	wooting_analog_read_analog

; 52   :         analog_d = wooting_analog_read_analog(KEY_D);

	mov	ecx, 7
	movaps	xmm7, xmm0
	call	wooting_analog_read_analog

; 53   : 
; 54   :         //error check
; 55   :         if (analog_w < 0.0f || analog_a < 0.0f ||
; 56   :             analog_s < 0.0f || analog_d < 0.0f) {

	comiss	xmm6, xmm10
	movaps	xmm8, xmm0
	ja	$LN7@main
	movss	xmm14, DWORD PTR __real@3f800000
	movss	xmm13, DWORD PTR __real@40800000
$LL2@main:
	comiss	xmm6, xmm9
	ja	$LN7@main
	comiss	xmm6, xmm7
	ja	$LN7@main
	comiss	xmm6, xmm8
	ja	$LN7@main

; 58   :             wooting_analog_uninitialise();
; 59   :             return 1;
; 60   :         }
; 61   : 
; 62   :         dx = analog_d - analog_a;

	subss	xmm8, xmm9

; 63   :         dy = analog_s - analog_w;
; 64   : 
; 65   :         //mouse accel
; 66   :         x.prev = x.current;
; 67   :         y.prev = y.current;
; 68   :         x.current = dx;
; 69   :         y.current = dy;
; 70   : 
; 71   :         accel = 1 + ((x.current - x.prev) + (y.current - y.prev)) / (float)dt;
; 72   : 
; 73   :         dx = LIN2EXPO(dx);
; 74   :         dy = LIN2EXPO(dy);
; 75   : 
; 76   :         input.mi.dx = (LONG)(dx * PROP * accel);
; 77   :         input.mi.dy = (LONG)(dy * PROP * accel);
; 78   : 
; 79   :         if (SendInput(1, &input, sizeof(input)) == 0) {

	mov	r8d, 40					; 00000028H
	subss	xmm7, xmm10
	mov	ecx, 1
	lea	rdx, QWORD PTR input$[rsp]
	movaps	xmm0, xmm8
	subss	xmm0, xmm11
	movaps	xmm2, xmm7
	subss	xmm2, xmm12
	movaps	xmm1, xmm7
	mulss	xmm1, xmm7
	addss	xmm2, xmm0
	mulss	xmm1, xmm13
	xorps	xmm0, xmm0
	cvtsi2ss xmm0, DWORD PTR ?dt@?1??main@@9@9
	mulss	xmm1, xmm7
	divss	xmm2, xmm0
	movaps	xmm0, xmm8
	addss	xmm1, xmm1
	mulss	xmm0, xmm8
	addss	xmm2, xmm14
	mulss	xmm0, xmm13
	mulss	xmm1, xmm2
	mulss	xmm0, xmm8
	addss	xmm0, xmm0
	mulss	xmm0, xmm2
	cvttss2si eax, xmm0
	mov	DWORD PTR input$[rsp+8], eax
	cvttss2si eax, xmm1
	mov	DWORD PTR input$[rsp+12], eax
	call	QWORD PTR __imp_SendInput
	test	eax, eax
	je	$LN12@main

; 83   :         }
; 84   :         
; 85   : 
; 86   :         Sleep(POLL_RATE);

	mov	ecx, 5
	movaps	xmm11, xmm8
	movaps	xmm12, xmm7
	call	QWORD PTR __imp_Sleep

; 87   :         dt = clock() - start;

	call	clock
	sub	eax, DWORD PTR ?start@?1??main@@9@9
	mov	DWORD PTR ?dt@?1??main@@9@9, eax
	call	clock
	mov	ecx, 26
	mov	DWORD PTR ?start@?1??main@@9@9, eax
	call	wooting_analog_read_analog
	mov	ecx, 4
	movaps	xmm10, xmm0
	call	wooting_analog_read_analog
	mov	ecx, 22
	movaps	xmm9, xmm0
	call	wooting_analog_read_analog
	mov	ecx, 7
	movaps	xmm7, xmm0
	call	wooting_analog_read_analog
	comiss	xmm6, xmm10
	movaps	xmm8, xmm0
	jbe	$LL2@main
$LN7@main:

; 57   :             fprintf(stderr, "Failed to read analog key values.\n");

	mov	ecx, 2
	call	__acrt_iob_func
	mov	rcx, rax
	lea	rdx, OFFSET FLAT:??_C@_0CD@NIDKDOEG@Failed?5to?5read?5analog?5key?5values@
	call	fprintf
$LN33@main:

; 81   :             wooting_analog_uninitialise();

	call	wooting_analog_uninitialise
	movaps	xmm13, XMMWORD PTR [rsp+96]

; 88   :     }
; 89   : }

	mov	eax, 1
	movaps	xmm14, XMMWORD PTR [rsp+80]
	movaps	xmm11, XMMWORD PTR [rsp+128]
	movaps	xmm10, XMMWORD PTR [rsp+144]
	movaps	xmm9, XMMWORD PTR [rsp+160]
	movaps	xmm8, XMMWORD PTR [rsp+176]
	movaps	xmm7, XMMWORD PTR [rsp+192]
	movaps	xmm6, XMMWORD PTR [rsp+208]
	movaps	xmm12, XMMWORD PTR [rsp+112]
	add	rsp, 224				; 000000e0H
	pop	rbx
	ret	0
$LN12@main:

; 80   :             fprintf(stderr, "SendInput failed: %lu\n", GetLastError());

	call	QWORD PTR __imp_GetLastError
	mov	ecx, 2
	mov	ebx, eax
	call	__acrt_iob_func
	mov	rcx, rax
	lea	rdx, OFFSET FLAT:??_C@_0BH@KOHKNOHN@SendInput?5failed?3?5?$CFlu?6@
	mov	r8d, ebx
	call	fprintf

; 82   :             return 1;

	jmp	SHORT $LN33@main
$LN5@main:

; 41   :         fprintf(stderr, "Failed to initialize Wooting Analog SDK: %d\n", init_result);

	mov	ecx, 2
	call	__acrt_iob_func
	mov	rcx, rax
	lea	rdx, OFFSET FLAT:??_C@_0CN@HBIOMAF@Failed?5to?5initialize?5Wooting?5Ana@
	mov	r8d, ebx
	call	fprintf

; 88   :     }
; 89   : }

	mov	eax, 1
	add	rsp, 224				; 000000e0H
	pop	rbx
	ret	0
main	ENDP
_TEXT	ENDS
END
